### ISSUE TITLE
2.0.1 - Unable to compile on XCode 8 using Swift 2.3 

### ISSUE THREAD

**Issue by obyrnesean** [svdo/swift-netutils#10]
I'm getting four redefinition errors in the module.modulemap. 

- Redefinition of module 'Compression'
- Redefinition of module 'Darwin'
- Redefinition of module 'os'
- Redefinition of module 'libkern'

I'm also getting an error in Interface.swift: Could not build Objective-C module 'ifaddrs'

I see that you have a commit in your 3.0.1 branch for fixing module.modulemap however making that change does not fix the errors for Swift 2.3. 

Would appreciate a build that corrects these errors for your 2.0.X branch.

Thanks!

**Comment by svdo** [comment]
Sorry for late response, I'm very busy at the moment. It doesn't look like I will be able to do this on the very short term. Pull request welcome though...

**Comment by svdo** [comment]
Had a quick look at this. I hope I'm not disappointing you too much, but I decided that I'm not going to support legacy versions of Swift. Please note that there is no Swift-2.3 branch in this repo... I don't have time to maintain two separate versions; if somebody else wants to step in and maintain legacy versions, please contact me, otherwise it's going to be only the latest version of Swift...
